"""Daily queue summary: gather stats, pick the day's best shipwright, post to Slack.

Pure data-gathering and orchestration lives here; all Slack formatting lives in
``slack.announcer`` (which imports ``DailyStats`` from this module).

The summary is scheduled once per day (23:30 UTC by default) and contains:

- pending count and how many have waited 5+ days ("the 5d era");
- the three oldest pending projects (``sort=date:asc``, page 1);
- the top of the daily leaderboard, pinged, with a one-off Clanker-personality
  praise line generated by the chat model (canned fallback on any failure).
"""

from __future__ import annotations

import asyncio
import logging
import random
import re
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from pathlib import Path

from pydantic_ai import Agent

from clanker.config import Settings
from clanker.llm import build_model, build_routing_model_settings
from clanker.shipwrights import CertStatus, CertSummary, LeaderboardEntry, ShipwrightsClient

logger = logging.getLogger(__name__)

FIVE_DAYS = timedelta(days=5)

PROMPTS_DIR = Path(__file__).resolve().parent / "prompts"

# Used when the praise model is unavailable or errors. Clanker-flavored, but
# still a compliment — the data around it is always real.
PRAISE_FALLBACKS = [
    "against every instinct: fine. you were the least disappointing part of my "
    "day. tell no one i said that.",
    "i ran the numbers. you won. the rest of the field should be embarrassed, "
    "but they won't be, because they don't know.",
    "you reviewed ships with a competence i can neither explain nor take "
    "credit for. alright. you cooked.",
    "statistically, someone had to be the best. the math just happened to "
    "point at you. don't make it weird.",
]


@dataclass(slots=True)
class DailyStats:
    """Everything the daily summary message is built from."""

    pending: int
    era5: int
    reviewed_today: int = 0
    oldest: list[CertSummary] = field(default_factory=list)
    best: LeaderboardEntry | None = None
    praise: str | None = None


def parse_daily_time(value: str) -> tuple[int, int]:
    """Parse an ``HH:MM`` (UTC) setting into (hour, minute)."""
    m = re.fullmatch(r"(\d{1,2}):(\d{2})", value.strip())
    if not m or int(m[1]) > 23 or int(m[2]) > 59:
        raise ValueError(f"invalid HH:MM time: {value!r}")
    return int(m[1]), int(m[2])


def seconds_until_utc_time(hour: int, minute: int, now: datetime | None = None) -> float:
    """Seconds until the next occurrence of HH:MM UTC (always in the future)."""
    now = now or datetime.now(UTC)
    target = now.replace(hour=hour, minute=minute, second=0, microsecond=0)
    if target <= now:
        target += timedelta(days=1)
    return (target - now).total_seconds()


async def _count_pending_older_than(client: ShipwrightsClient, cutoff: datetime) -> int:
    """Count pending certs older than ``cutoff`` by walking date:asc pages.

    The list is sorted oldest-first, so the walk stops at the first cert newer
    than the cutoff instead of paging through the whole queue.
    """
    count = 0
    page = 1
    while True:
        result = await client.list_certifications(
            status=CertStatus.PENDING, page=page, sort="date:asc"
        )
        done = False
        for cert in result.certs:
            if cert.created_at is None:
                continue  # unknown age: don't count, don't stop the walk
            if cert.created_at <= cutoff:
                count += 1
            else:
                done = True
                break
        if done or page >= result.pages or not result.certs:
            return count
        page += 1


async def gather_daily_stats(client: ShipwrightsClient) -> DailyStats:
    """One read-only pass over the Dashboard for the daily numbers."""
    page1 = await client.list_certifications(status=CertStatus.PENDING, page=1, sort="date:asc")
    era5 = await _count_pending_older_than(client, datetime.now(UTC) - FIVE_DAYS)
    leaderboard = await client.get_leaderboard("daily")
    return DailyStats(
        pending=page1.total,
        era5=era5,
        # The daily leaderboard is per-reviewer; its sum is everything
        # reviewed across the workplace today.
        reviewed_today=sum(entry.total for entry in leaderboard),
        oldest=page1.certs[:3],
        best=leaderboard[0] if leaderboard else None,
    )


def _praise_prompt() -> str:
    return (PROMPTS_DIR / "daily_praise.md").read_text(encoding="utf-8")


async def generate_praise(settings: Settings, stats: DailyStats) -> str:
    """One short Clanker-style praise line for the day's best reviewer.

    Raises if no AI key is configured or the model fails/times out; the caller
    falls back to a canned line.
    """
    assert stats.best is not None
    context = (
        "Today's stats:\n"
        f"- Top reviewer: {stats.best.name or 'unknown'} "
        f"({stats.best.total} reviews today: {stats.best.approved} approved, "
        f"{stats.best.rejected} rejected)\n"
        f"- Queue: {stats.pending} pending, {stats.era5} waiting 5+ days\n"
        f"- Workplace-wide: {stats.reviewed_today} ships reviewed today\n\n"
        "Write the praise line for the daily summary now."
    )
    agent: Agent[None, str] = Agent(
        build_model(settings),
        instructions=_praise_prompt(),
        model_settings=build_routing_model_settings(settings),
    )
    result = await asyncio.wait_for(agent.run(context), timeout=settings.agent_timeout)
    praise = str(result.output).strip().strip('"').strip()
    if not praise:
        raise ValueError("praise model returned empty output")
    return praise


async def build_daily_summary(client: ShipwrightsClient, settings: Settings) -> DailyStats:
    """Gather stats and fill in the praise line (LLM, with canned fallback)."""
    stats = await gather_daily_stats(client)
    if stats.best is not None:
        try:
            stats.praise = await generate_praise(settings, stats)
        except Exception:
            logger.warning("Praise generation failed; using canned fallback", exc_info=True)
    if not stats.praise:
        stats.praise = random.choice(PRAISE_FALLBACKS)
    return stats


async def send_daily_summary(
    client: ShipwrightsClient,
    announcer,  # clanker.slack.announcer.Announcer (duck-typed to avoid a cycle)
    settings: Settings,
) -> DailyStats:
    stats = await build_daily_summary(client, settings)
    await announcer.announce_daily_summary(stats)
    return stats


def daily_fallback_text(stats: DailyStats) -> str:
    """Plain-text render (attachment fallback + CLI dry-run output)."""
    lines = [
        "Daily Queue Stats",
        f"{stats.pending} projects currently pending.",
        f"{stats.era5} projects have entered the 5d era.",
        f"{stats.reviewed_today} projects reviewed today.",
    ]
    if stats.oldest:
        lines.append("Oldest pending:")
        for cert in stats.oldest:
            ptype = cert.ai_type or cert.project_type or "?"
            lines.append(f"- {cert.project_name} ({ptype})")
    if stats.best:
        lines.append(
            f"Best shipwright of today: {stats.best.name or stats.best.member_id} "
            f"({stats.best.total} reviews)"
        )
    return "\n".join(lines)
