"""Code-only video director for first-layer rejections (no model involved).

The first-layer review already knows *why* it rejected, so code picks each scene's page,
caption, and highlight. Captions use the same casual Shipwright voice as the reject
message; nothing is generated by a model, so the video can't read as AI-written.

Reasons with no public page that shows the problem (raw README link, missing banner,
"untitled" name, ...) become text cards rendered locally instead of a live capture.
"""

from __future__ import annotations

import hashlib
import html
import random
import re
from collections.abc import Sequence
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

from clanker.forges import Repo, parse_repo
from clanker.review.models import VideoEvidence
from clanker.review.reject_message import BANNER_WHAT, ORDER, RejectContext, raw_readme_url
from clanker.review.video.capture import VIEWPORT
from clanker.review.video.models import (
    DirectedScene,
    EvidenceCapture,
    SceneRole,
    VideoPlan,
    VideoProject,
)

MAX_SCENES = 3


@dataclass(slots=True)
class SceneSpec:
    """One planned scene: either a live page capture or a local text card."""

    id: str
    reason: str
    title: str
    caption: str
    fix: str
    url: str | None = None  # None -> text card
    card_lines: list[str] = field(default_factory=list)
    highlight: str | None = None


@dataclass(slots=True)
class RejectVideoInputs:
    """Facts the template director needs; all come from the first-layer review."""

    ctx: RejectContext
    repo_url: str | None = None
    commit: str | None = None  # submission-time commit (short or full SHA)
    banner_url: str | None = None
    readme_markdown: str = ""
    flagged_code: dict[str, str] = field(default_factory=dict)  # path -> excerpt
    project_name: str = ""


def _repo(inputs: RejectVideoInputs) -> Repo | None:
    return parse_repo(inputs.repo_url)


def _readme_heading(markdown: str) -> str | None:
    for line in markdown.splitlines():
        m = re.match(r"\s{0,3}#{1,3}\s+(.+?)\s*#*\s*$", line)
        if m and len(m.group(1)) >= 3:
            return re.sub(r"[*_`]", "", m.group(1)).strip()
    return None


def plan_scenes(reasons: Sequence[str], inputs: RejectVideoInputs, seed: str) -> list[SceneSpec]:
    """Map reject reasons to at most three scenes, most blocking first (same order as the
    message). AI-undeclared merges into the AI-code scene; AI + thin README share one scene."""
    rng = random.Random(int(hashlib.sha256(seed.encode()).hexdigest()[:16], 16))
    ctx = inputs.ctx
    repo = _repo(inputs)
    ref = inputs.commit or "HEAD"
    blob = (lambda path: repo.blob_url(ref, path)) if repo else None
    readme_url = blob("README.md") if blob else None
    wanted = [r for r in ORDER if r in set(reasons)]
    if "ai_code" in wanted and "ai_undeclared" in wanted:
        wanted.remove("ai_undeclared")
    if "ai_readme" in wanted and "readme_thin" in wanted:
        wanted.remove("readme_thin")

    specs: list[SceneSpec] = []
    for reason in wanted:
        pick = rng.choice
        if reason in ("ai_code", "ai_undeclared") and inputs.flagged_code and blob:
            path, excerpt = next(
                (
                    (p, e)
                    for p, e in inputs.flagged_code.items()
                    if p.lower().endswith((".css", ".scss"))
                ),
                next(iter(inputs.flagged_code.items())),
            )
            undeclared = "ai_undeclared" in reasons
            specs.append(
                SceneSpec(
                    id="ai-code",
                    reason=reason,
                    url=blob(path),
                    # No highlight on purpose: pointing at a line suggests deleting it is
                    # the fix. The whole project needs to become the author's own work.
                    highlight=None,
                    title=pick(["Most of this is AI-generated", "This reads mostly AI-written"]),
                    caption=(
                        "The project is well over our 30% AI limit. Small edits won't be "
                        "enough: redo the design and code yourself and build features you "
                        "came up with."
                        + (" Please also declare your AI use honestly." if undeclared else "")
                    ),
                    fix="Rebuild the design and code yourself, with your own features"
                    + (", and declare AI use" if undeclared else ""),
                )
            )
        elif reason in ("ai_readme", "readme_thin", "needs_api_key", "readme_not_english") and (
            readme_url
        ):
            both = "ai_readme" in reasons and "readme_thin" in reasons
            title = {
                "ai_readme": "The README reads AI-written",
                "readme_thin": "The README needs more detail",
                "needs_api_key": "It needs your own API key",
                "readme_not_english": "The README isn't in English",
            }[reason]
            caption = {
                "ai_readme": "Write it yourself from scratch: what you built, how and why you "
                "built it, and how to use it. Editing the AI text won't be enough."
                + (" It also needs more detail." if both else ""),
                "readme_thin": "Add what the project does, its features, how to use it and how you "
                "made it.",
                "needs_api_key": "Reviewers can't bring their own key. Include a working key or "
                "proxy (Hack Club AI is a free option).",
                "readme_not_english": "Write it in English, or link an English version at the "
                "top.",
            }[reason]
            # AI README: no highlight, for the same reason as AI code (the whole README is the
            # problem, not a line). Thin README: the heading shows how little is there.
            highlight = (
                None
                if reason in ("ai_readme", "readme_not_english")
                else _readme_heading(inputs.readme_markdown)
                if reason == "readme_thin"
                else next(
                    (w for w in ("API key", "api key", "API_KEY") if w in inputs.readme_markdown),
                    None,
                )
            )
            specs.append(
                SceneSpec(
                    id=reason.replace("_", "-"),
                    reason=reason,
                    url=readme_url,
                    highlight=highlight,
                    title=title,
                    caption=caption,
                    fix={
                        "ai_readme": "Write the README yourself, from scratch",
                        "readme_thin": "Expand the README",
                        "needs_api_key": "Make the demo work without a user API key",
                        "readme_not_english": "Write the README in English",
                    }[reason],
                )
            )
        elif reason == "readme_not_raw":
            raw = raw_readme_url(ctx.readme_url, ctx.repo_url)
            # Open the link they actually set (the README page, not the raw file) when it's
            # a real page; the caption says what to use instead.
            current = ctx.readme_url if (ctx.readme_url or "").startswith("http") else None
            specs.append(
                SceneSpec(
                    id="readme-link",
                    reason=reason,
                    url=current,
                    title="The README link isn't raw",
                    caption=(
                        f"Stardance needs the raw file. Set the README link to {raw}"
                        if raw and len(raw) <= 170
                        else "Stardance needs the raw file. Open your README, click Raw and "
                        "use that link in your project settings."
                    ),
                    card_lines=[
                        f"now:  {ctx.readme_url or '(not set)'}",
                        f"use:  {raw or 'the raw file link'}",
                    ],
                    fix="Set the README link to the raw file",
                )
            )
        elif (
            reason
            in (
                "demo_broken",
                "demo_is_video",
                "demo_is_repo",
                "bad_hosting",
                "itch_no_build",
                "bot_link_invalid",
            )
            and ctx.demo_url
        ):
            title, caption, fix = {
                "demo_broken": (
                    "The demo doesn't load",
                    "The demo page shows an error right now. Check your deployment and reship.",
                    "Fix the demo deployment",
                ),
                "demo_is_video": (
                    "The demo is a video",
                    "The demo needs to let people actually try the project.",
                    "Link a demo people can use",
                ),
                "demo_is_repo": (
                    "The demo is the repo",
                    "Link the live site, a release build or the package page instead.",
                    "Change the demo link",
                ),
                "bad_hosting": (
                    "This host sleeps",
                    "Free Render/Railway/Streamlit-style hosts "
                    "sleep or load slowly. Use Vercel, Netlify or GitHub Pages.",
                    "Move the demo to permanent hosting",
                ),
                "itch_no_build": (
                    "No build on the itch page",
                    "Upload a downloadable or browser-playable build.",
                    "Add a build to the itch page",
                ),
                "bot_link_invalid": (
                    "People can't try the bot here",
                    "Link a channel or server invite where the bot runs.",
                    "Link a channel for the bot",
                ),
            }[reason]
            specs.append(
                SceneSpec(
                    id=reason.replace("_", "-"),
                    reason=reason,
                    url=ctx.demo_url,
                    title=title,
                    caption=caption,
                    fix=fix,
                    highlight=("Bad gateway" if reason == "demo_broken" else None),
                )
            )
        elif reason == "missing_build" and repo:
            specs.append(
                SceneSpec(
                    id="missing-build",
                    reason=reason,
                    url=repo.releases_url,
                    title="No build in the release",
                    fix="Upload a build to a release",
                    caption="Reviewers need something to download and run, not just the source.",
                )
            )
        elif reason in ("banner_bad", "banner_default"):
            if reason == "banner_bad" and inputs.banner_url:
                specs.append(
                    SceneSpec(
                        id="banner",
                        reason=reason,
                        url=inputs.banner_url,
                        title="The banner needs to show the project",
                        caption=(
                            "Use a screenshot of your project in action, not "
                            f"{BANNER_WHAT.get(ctx.banner_label or '', 'a logo or other art')}. "
                            "You can change it in project settings."
                        ),
                        fix="Change the banner to a screenshot of the project",
                    )
                )
            else:
                specs.append(
                    SceneSpec(
                        id="banner",
                        reason=reason,
                        title="There's no banner yet",
                        caption="Add a screenshot of your project in action in project settings.",
                        card_lines=["banner:  (default)"],
                        fix="Add a project banner",
                    )
                )
        elif reason in ("no_source", "no_readme") and repo:
            specs.append(
                SceneSpec(
                    id=reason.replace("_", "-"),
                    reason=reason,
                    url=repo.web_url,
                    title="The source isn't here" if reason == "no_source" else "There's no README",
                    caption="Push the project's source code to the repo."
                    if reason == "no_source"
                    else "Add a README explaining what it is and how to use it.",
                    fix="Push the source code" if reason == "no_source" else "Add a README",
                )
            )
        elif reason == "untitled":
            specs.append(
                SceneSpec(
                    id="untitled",
                    reason=reason,
                    title="The project needs a name",
                    caption="Give it a real name in project settings.",
                    card_lines=[f"name:  {inputs.project_name or 'untitled'}"],
                    fix="Rename the project",
                )
            )
        if not specs or specs[-1].reason != reason:
            # No live page for this reason (unsupported repo host, no demo link, ...):
            # every reject reason still gets a scene, as a text card.
            specs.append(_fallback_card(reason, inputs, repo))
        if len(specs) >= MAX_SCENES:
            break
    return specs


# Text-card wording for every reject reason: (title, caption, fix).
FALLBACK_CARDS: dict[str, tuple[str, str, str]] = {
    "no_source": (
        "The source isn't here",
        "Push the project's source code to the repo.",
        "Push the source code",
    ),
    "no_readme": (
        "There's no README",
        "Add a README explaining what it is and how to use it.",
        "Add a README",
    ),
    "pre_event_undeclared": (
        "Started before Stardance",
        "This repo has work from before June 1st. Mark the project as an update when you "
        "reship.",
        "Mark it as an updated project",
    ),
    "readme_not_english": (
        "The README isn't in English",
        "Write it in English, or link an English version at the top.",
        "Write the README in English",
    ),
    "untitled": (
        "The project needs a name",
        "Give it a real name in project settings.",
        "Rename the project",
    ),
    "readme_not_raw": (
        "The README link isn't raw",
        "Stardance needs the raw file so it can render it. Swap the link in your project "
        "settings.",
        "Set the README link to the raw file",
    ),
    "bad_hosting": (
        "This host sleeps",
        "Free Render/Railway/Streamlit-style hosts sleep or load slowly. Use Vercel, Netlify "
        "or GitHub Pages.",
        "Move the demo to permanent hosting",
    ),
    "demo_is_repo": (
        "The demo is the repo",
        "Link the live site, a release build or the package page instead.",
        "Change the demo link",
    ),
    "demo_is_video": (
        "The demo is a video",
        "The demo needs to let people actually try the project.",
        "Link a demo people can use",
    ),
    "missing_build": (
        "No build in the release",
        "Reviewers need something to download and run, not just the source.",
        "Upload a build to a release",
    ),
    "itch_no_build": (
        "No build on the itch page",
        "Upload a downloadable or browser-playable build.",
        "Add a build to the itch page",
    ),
    "bot_link_invalid": (
        "People can't try the bot here",
        "Link a channel or server invite where the bot runs.",
        "Link a channel for the bot",
    ),
    "demo_broken": (
        "The demo doesn't load",
        "The demo page shows an error right now. Check your deployment and reship.",
        "Fix the demo deployment",
    ),
    "needs_api_key": (
        "It needs your own API key",
        "Reviewers can't bring their own key. Include a working key or proxy (Hack Club AI "
        "is a free option).",
        "Make the demo work without a user API key",
    ),
    "banner_default": (
        "There's no banner yet",
        "Add a screenshot of your project in action in project settings.",
        "Add a project banner",
    ),
    "banner_bad": (
        "The banner should show the project",
        "Use a screenshot of your project in action. Change it in project settings.",
        "Swap the banner for a real screenshot",
    ),
    "ai_code": (
        "Most of this is AI-generated",
        "The project is well over our 30% AI limit. Small edits won't be enough: redo the "
        "design and code yourself and build features you came up with.",
        "Rebuild the design and code yourself, with your own features",
    ),
    "ai_undeclared": (
        "AI use isn't declared",
        "It looks like AI was used, but the AI declaration doesn't say so. Please declare it "
        "honestly.",
        "Declare your AI use honestly",
    ),
    "ai_readme": (
        "The README reads AI-written",
        "Write it yourself from scratch: what you built, how and why you built it, and how to "
        "use it. Editing the AI text won't be enough.",
        "Write the README yourself, from scratch",
    ),
    "readme_thin": (
        "The README needs more detail",
        "Add what the project does, its features, how to use it and how you made it.",
        "Expand the README",
    ),
    "feedback_ignored": (
        "The last feedback isn't addressed yet",
        "Please make the changes from the previous review before reshipping.",
        "Address the previous review's feedback",
    ),
    "not_eligible": (
        "This project isn't eligible",
        "It looks like a school assignment or otherwise outside the program's rules.",
        "Check the eligibility rules",
    ),
}


def _fallback_card(reason: str, inputs: RejectVideoInputs, repo: Repo | None) -> SceneSpec:
    ctx = inputs.ctx
    title, caption, fix = FALLBACK_CARDS.get(
        reason, ("This needs a fix", "See the review message for details.", "See the review")
    )
    if reason.startswith(("demo_", "bad_hosting", "itch_", "bot_", "needs_api")):
        lines = [f"demo:  {ctx.demo_url or '(not set)'}"]
    elif reason.startswith(("readme_", "ai_readme", "no_readme")):
        lines = [f"README:  {ctx.readme_url or '(not set)'}"]
    elif reason.startswith("banner_"):
        lines = [f"banner:  {inputs.banner_url or '(default)'}"]
    elif reason == "missing_build" and repo:
        lines = [f"releases:  {repo.releases_url}"]
    elif reason == "untitled":
        lines = [f"name:  {inputs.project_name or 'untitled'}"]
    else:
        lines = [f"repo:  {inputs.repo_url or ctx.repo_url or '(not set)'}"]
    return SceneSpec(
        id=reason.replace("_", "-"),
        reason=reason,
        title=title,
        caption=caption,
        card_lines=lines,
        fix=fix,
    )


def evidence_for(specs: Sequence[SceneSpec]) -> list[VideoEvidence]:
    """Live-capture scenes as VideoEvidence for the existing capture step."""
    return [
        VideoEvidence(id=s.id, check=s.reason, url=s.url, finding=s.caption) for s in specs if s.url
    ]


async def render_text_card(spec: SceneSpec, output_dir: Path) -> EvidenceCapture:
    """Render a text-card 'screenshot' locally (no network): a plain text page, so it looks
    like any other tab in the browser-style video."""
    from playwright.async_api import async_playwright

    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"{spec.id}.png"
    lines = "".join(f"<div class='line'>{html.escape(line)}</div>" for line in spec.card_lines)
    document = f"""<!doctype html><html><head><meta charset="utf-8"><style>
html,body{{margin:0;width:{VIEWPORT["width"]}px;height:{VIEWPORT["height"]}px;background:#fff;
font-family:"DejaVu Sans Mono","Liberation Mono",ui-monospace,monospace;color:#111}}
.wrap{{position:absolute;left:8px;top:8px;right:8px}}
.line{{font-size:15px;line-height:1.5;white-space:pre-wrap;word-break:break-all}}
</style></head><body><div class="wrap">{lines}</div>
</body></html>"""
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        page = await browser.new_page(viewport=VIEWPORT)
        await page.set_content(document)
        await page.screenshot(path=str(path))
        await browser.close()
    return EvidenceCapture(
        evidence_id=spec.id,
        requested_url="",
        final_url="",
        captured_at=datetime.now(UTC),
        screenshot_path=path,
        viewport_width=VIEWPORT["width"],
        viewport_height=VIEWPORT["height"],
    )


HEADLINES = [
    "A few things to fix before reshipping",
    "Almost there, a few fixes first",
    "Not quite ready yet",
]


class TemplateDirector:
    """Director-protocol implementation with zero model calls."""

    model_calls = 0

    def __init__(self, specs: Sequence[SceneSpec], seed: str) -> None:
        self._specs = {s.id: s for s in specs}
        self._rng = random.Random(int(hashlib.sha256(seed.encode()).hexdigest()[:16], 16))

    async def direct(
        self,
        project: VideoProject,
        evidence: Sequence[VideoEvidence],
        captures: Sequence[EvidenceCapture],
    ) -> VideoPlan:
        captured = {c.evidence_id for c in captures}
        scenes = [
            DirectedScene(
                evidence_id=s.id,
                role=SceneRole.PRIMARY,
                title=s.title[:80],
                explanation=s.caption[:260],
                highlight_text=s.highlight,
            )
            for s in self._specs.values()
            if s.id in captured
        ]
        count = len(scenes)
        return VideoPlan(
            headline=self._rng.choice(HEADLINES),
            summary=(
                "One thing to fix, then reship."
                if count == 1
                else f"{count} things to fix, then reship."
            ),
            scenes=scenes,
        )
